flowchart LR

    WebClient
    WebServer

    JobQueue
    ResultQueue

    CodeAster

    WebClient --> WebServer

    WebServer --put--> JobQueue

    JobQueue --get--> CodeAster

    CodeAster --put--> ResultQueue

    ResultQueue --get--> WebServer

